export const LOGIN_ATTEMPT = "LOGIN_ATTEMPT";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const ADD_QUESTION_ATTEMPT = "ADD_QUESTION_ATTEMPT";
export const ADD_QUESTION_SUCCESS = "ADD_QUESTION_SUCCESS";
export const ADD_MESSAGE = "ADD_MESSAGE";
export const FETCH_QUESTIONS_ATTEMPT = "FETCH_QUESTIONS_ATTEMPT";
export const FETCH_QUESTIONS_SUCCESS = "FETCH_QUESTIONS_SUCCESS";
export const DELETE_QUESTION_SUCCESS = "DELETE_QUESTION_SUCCESS";
export const LOGOUT = "LOGOUT";

export const FETCH_PROFILE_ATTEMPT = "FETCH_PROFILE_ATTEMPT";
export const FETCH_PROFILE_SUCCESS = "FETCH_PROFILE_SUCCESS";
export const UNMOUNT_PROFILE = "UNMOUNT_PROFILE";

export const FETCH_QUESTION_ATTEMPT = "FETCH_QUESTION_ATTEMPT";
export const FETCH_QUESTION_SUCCESS = "FETCH_QUESTION_SUCCESS";
export const UNMOUNT_QUESTION = "UNMOUNT_QUESTION";

export const FETCH_CONVERSATION_ATTEMPT = "FETCH_CONVERSATION_ATTEMPT";
export const FETCH_CONVERSATION_SUCCESS = "FETCH_CONVERSATION_SUCCESS";

export const FETCH_ANSWERS_ATTEMPT = "FETCH_ANSWERS_ATTEMPT";
export const FETCH_ANSWERS_SUCCESS = "FETCH_ANSWERS_SUCCESS";
export const UNMOUNT_ANSWERS = "UNMOUNT_ANSWERS";

export const ADD_ANSWER_ATTEMPT = "ADD_ANSWER_ATTEMPT";
export const ADD_ANSWER_SUCCESS = "ADD_ANSWER_SUCCESS";
